sudo: false
language: node_js
node_js:
- '18'
services: mongodb
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- corepack enable
install:
- pnpm install
- pnpm run test:ci
- pnpm run coveralls